"use client";

import CommonWrapper from "@/common/CommonWrapper";
import { ShieldCheck } from "lucide-react";

export const IntegrityEngine = () => {
    return (
        <section className="py-[80px] md:py-[120px] relative overflow-hidden bg-[#020617] border-t border-white/5">
            <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-primary/5 rounded-full blur-[180px] pointer-events-none" />
            <CommonWrapper className="max-w-[1200px] px-5 md:px-[48px]">
                <div className="text-center mb-24 space-y-4">
                    <div className="text-[10.5px] text-primary/80 font-bold uppercase tracking-[4px] font-mono">AI INTEGRITY ENGINE</div>
                    <h2 className="font-cormorant font-bold text-[clamp(28px,3.2vw,48px)] leading-[1.2] text-white">The AI Knows You. <span className="text-gold2 italic">From the First Response.</span></h2>
                    <p className="text-white/60 text-[16px] max-w-3xl mx-auto font-outfit leading-[1.8] text-center">
                        From the moment a practitioner begins their Micro-Credential, the AI engine is doing far more than teaching. It is building a deep, dynamic profile of that specific learner. This profile grows richer with every interaction.
                    </p>
                </div>

                <div className="grid md:grid-cols-3 gap-8">
                    {[
                        {
                            id: "A",
                            title: "Language Fingerprint",
                            desc: "Every person writes in a way that is uniquely theirs. Vocabulary choices, sentence construction, response patterns, and even the way they express uncertainty, all create a recognizable signature. The AI records this from the very first interaction."
                        },
                        {
                            id: "B",
                            title: "Knowledge Baseline",
                            desc: "The pre-test establishes what the practitioner knows before instruction begins. This baseline is stored. If the quality of responses suddenly jumps beyond what the baseline would predict, the system flags this as an inconsistency."
                        },
                        {
                            id: "C",
                            title: "Behavioral Consistency",
                            desc: "The AI monitors the pace of responses, the nature of errors, and how the learner navigates difficulty. A practitioner who consistently struggles does not suddenly produce flawless academic language without reason. Patterns matter."
                        }
                    ].map((card, i) => (
                        <div key={i} className="p-12 rounded-[28px] bg-white/5 border border-white/10 space-y-8 relative group hover:border-primary/40 transition-all backdrop-blur-[6px]">
                            <div className="text-6xl font-bold text-primary/20 absolute top-8 left-10 group-hover:text-primary/30 transition-colors font-cormorant">{card.id}</div>
                            <div className="space-y-4 pt-12">
                                <h3 className="text-[22px] font-bold text-white font-outfit">{card.title}</h3>
                                <p className="text-white/60 leading-[1.75] font-outfit text-[15px]">{card.desc}</p>
                            </div>
                        </div>
                    ))}
                </div>

                {/* Academic Integrity Box */}
                <div className="mt-20 p-10 md:p-14 rounded-[32px] bg-gradient-to-br from-primary/10 to-transparent border border-primary/20 mx-auto space-y-10 backdrop-blur-[6px]">
                    <div className="flex items-center gap-5 text-primary">
                        <ShieldCheck className="w-10 h-10" />
                        <h3 className="text-[24px] md:text-[28px] font-bold font-cormorant">Academic Integrity: Why copying from another AI does not work</h3>
                    </div>
                    <div className="grid gap-8 text-white/60 text-[16px] leading-[1.8] font-outfit">
                        <p>
                            Some learners may attempt to copy a response generated by another AI tool on a separate device and paste it into the IKON SKILLS™ assessment. Here is why this strategy fails, not because of a simple plagiarism checker, but because of how deeply the AI understands the practitioner.
                        </p>
                        <p>
                            By the time a practitioner reaches an assessment question, the AI already has a detailed profile: how this person writes, what vocabulary they use, how they structure ideas, and what gaps they have shown. A response generated by a general AI tool will almost certainly <span className="text-white font-bold underline decoration-primary/40 underline-offset-4">not match this established profile.</span> The language will be too formal, too structured, or too advanced. The AI engine will detect this inconsistency immediately.
                        </p>
                        <p>
                            Furthermore, the assessment questions themselves are <span className="text-white font-bold">algorithmically personalized.</span> They are drawn from a question bank and sequenced based on the specific learner&apos;s progress. A general AI tool without access to this context cannot generate a contextually accurate answer.
                        </p>
                        <p className="border-t border-white/10 pt-8 text-[#49cbc7] font-medium italic text-[18px]">
                            This is not a system trying to catch cheaters after the fact. It is a system that knows each learner so well that inauthenticity becomes visible the moment it appears.
                        </p>
                    </div>
                </div>
            </CommonWrapper>
        </section>
    );
};
